[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "8M1NkwKGkrz8GrbWyCrvuEsHqrrt4UNnDaJsbhghCYyv"
magicblock = "D6vA4ET7JpNV7xatvQoU5PiB6ZAjkwLfn3mwc9ED8zJi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
